#ifndef MEDIADIALOG_H
#define MEDIADIALOG_H


#include <QDialog>
#include <QSharedPointer>


#include "Media.h" // forward model dependency
#include "MediaFactory.h"


// ui header generated by uic from MediaDialog.ui
namespace Ui { class MediaDialog; }


class MediaDialog : public QDialog {
Q_OBJECT
public:
explicit MediaDialog(QWidget* parent = nullptr, QSharedPointer<Media> mediaPassed = {});
~MediaDialog() override;


// after exec(), call this if accepted()
QSharedPointer<Media> getResult() const;
QString selectedType() const;


private slots:
void onTypeChanged(int index);
void onAccepted();
void onRejected();


private:
void populateFromMedia(const QSharedPointer<Media>& media);
bool validateInputs() const;
QSharedPointer<Media> buildMediaFromForm() const;


Ui::MediaDialog* ui;
QSharedPointer<Media> m_original;
QSharedPointer<Media> m_result;
};


#endif // MEDIADIALOG_H